# Generated by Django 4.2.6 on 2023-11-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelter_name', models.CharField(max_length=50)),
                ('shelter_email', models.CharField(max_length=100)),
                ('shelter_phone', models.CharField(max_length=15)),
                ('shelter_address', models.CharField(max_length=100)),
                ('shelter_city', models.CharField(max_length=50)),
                ('shelter_state', models.CharField(max_length=50)),
                ('shelter_zipcode', models.CharField(max_length=20)),
                ('shelter_employees_count', models.IntegerField(default=0)),
                ('shelter_pets_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('is_employee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'UserInformation',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('fixed', models.BooleanField()),
                ('pet_shelter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='website.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to='website.userinformation')),
                ('salary', models.PositiveIntegerField(default=0)),
                ('employee_shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.shelter')),
            ],
        ),
    ]
